version: 2.1

jobs:
    update-and-build:
        macos:
            xcode: 14.2.0
        steps:
            - checkout  # pull down code from
            - run:
                name: Update to latest package versions and build
                command: |-
                    for i in `ls -d */`
                    do
                        folder="${i%/*}"
                        cd $folder
                        xcodebuild -resolvePackageDependencies
                        BUILD_FILE="build.sh"
                        if [ -f "$BUILD_FILE" ]; then
                            sh build.sh
                        fi
                        cd ..
                    done

workflows:
    version: 2
    update-and-build:
        jobs:
            - update-and-build:
                context:
                    - org-global
                    - mobile
